import 'package:jewelry_management_app/models/order_details.dart';
import 'package:jewelry_management_app/models/user.dart';
import 'package:jewelry_management_app/models/jewelry.dart';
import 'package:jewelry_management_app/models/order.dart';

// Dữ liệu mẫu cho users
final users = [
  User(
    id: '1',
    username: 'admin',
    fullName: 'John Doe',
    gender: 1,
    email: 'johndoe@example.com',
    password: 'hashed_password_here',
    isAdmin: true,
    isActive: true,
    phone: '0123456789',
    dateOfBirth: DateTime.parse('2000-01-01T00:00:00.000'),
    address: 'Hà Nội',
    avatar: null,
    createdAt: DateTime.parse('2024-06-06T12:00:00.000'),
    updatedAt: null,
    isDeleted: true,
  ),
  User(
    id: '2',
    username: 'user01',
    fullName: 'Nguyễn Văn A',
    gender: 1,
    email: 'user01@example.com',
    password: 'hashed_password_01',
    isAdmin: false,
    isActive: true,
    phone: '0987654321',
    dateOfBirth: DateTime.parse('1995-05-15T00:00:00.000'),
    address: 'Tp.HCM',
    avatar: null,
    createdAt: DateTime.parse('2024-06-07T10:00:00.000'),
    updatedAt: null,
    isDeleted: false,
    ),
    User(
      id: '3',
      username: 'user02',
      fullName: 'Trần Thị B',
      gender: 0,
      email: 'user02@example.com',
      password: 'hashed_password_02',
      isAdmin: false,
      isActive: true,
      phone: '0912345678',
      dateOfBirth: DateTime.parse('1998-08-20T00:00:00.000'),
      address: 'Đà Nẵng',
      avatar: null,
      createdAt: DateTime.parse('2024-06-07T11:00:00.000'),
      updatedAt: null,
      isDeleted: false,
    ),
    User(
      id: '4',
      username: 'user03',
      fullName: 'Lê Văn C',
      gender: 1,
      email: 'user03@example.com',
      password: 'hashed_password_03',
      isAdmin: false,
      isActive: true,
      phone: '0909123456',
      dateOfBirth: DateTime.parse('1992-12-12T00:00:00.000'),
      address: 'Cần Thơ',
      avatar: null,
      createdAt: DateTime.parse('2024-06-07T12:00:00.000'),
      updatedAt: null,
      isDeleted: false,
    ),

];

// Dữ liệu mẫu cho jewelries
final jewelries = [
  Jewelry(
    id: '1',
    name: 'Nhẫn Vàng 18K Đính Kim Cương',
    description:
        'Nhẫn vàng 18K với kim cương tự nhiên 0.5 carat, thiết kế tinh tế, phù hợp cho lễ đính hôn và cưới hỏi',
    price: 25000000,
    imageUrls: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=400&fit=crop',
    ],
    category: 'Nhẫn',
    rating: 4.9,
    reviewCount: 127,
    material: 'Vàng 18K',
    gemstone: 'Kim cương',
    size: '16',
    color: 'Vàng',
    brand: 'Diamond Palace',
    stockQuantity: 5,
    weight: 3.2,
    origin: 'Việt Nam',
    isCertified: true,
    certificateNumber: 'GIA-2023-001',
  ),
  Jewelry(
    id: '2',
    name: 'Dây Chuyền Bạc Ý 925',
    description:
        'Dây chuyền bạc Ý 925 cao cấp, thiết kế cổ điển, phù hợp cho cả nam và nữ',
    price: 1500000,
    imageUrls: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=400&fit=crop',
    ],
    category: 'Dây chuyền',
    rating: 4.6,
    reviewCount: 89,
    material: 'Bạc 925',
    size: '50cm',
    color: 'Bạc',
    brand: 'Silver Star',
    stockQuantity: 15,
    weight: 12.5,
    origin: 'Ý',
    isCertified: false,
  ),
  Jewelry(
    id: '3',
    name: 'Bông Tai Ngọc Trai Akoya',
    description:
        'Bông tai ngọc trai Akoya tự nhiên từ Nhật Bản, kích thước 8-9mm, ánh sáng tuyệt đẹp',
    price: 8500000,
    imageUrls: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=400&fit=crop',
    ],
    category: 'Bông tai',
    rating: 4.8,
    reviewCount: 156,
    material: 'Vàng trắng 14K',
    gemstone: 'Ngọc trai Akoya',
    size: '8-9mm',
    color: 'Trắng',
    brand: 'Pearl Beauty',
    stockQuantity: 8,
    weight: 2.1,
    origin: 'Nhật Bản',
    isCertified: true,
    certificateNumber: 'PEARL-2023-002',
  ),
  Jewelry(
    id: '4',
    name: 'Lắc Tay Vàng Hồng 10K',
    description:
        'Lắc tay vàng hồng 10K trẻ trung, thiết kế hiện đại, phù hợp cho phái nữ',
    price: 4200000,
    imageUrls: [
      'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=400&fit=crop',
    ],
    category: 'Lắc tay',
    rating: 4.5,
    reviewCount: 203,
    material: 'Vàng hồng 10K',
    size: '18cm',
    color: 'Vàng hồng',
    brand: 'Rose Gold',
    stockQuantity: 12,
    weight: 8.7,
    origin: 'Hàn Quốc',
    isCertified: false,
  ),
  Jewelry(
    id: '5',
    name: 'Đồng Hồ Rolex Submariner',
    description:
        'Đồng hồ Rolex Submariner thép không gỉ, chống nước 300m, máy cơ tự động',
    price: 280000000,
    imageUrls: [
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&h=400&fit=crop',
    ],
    category: 'Đồng hồ',
    rating: 5.0,
    reviewCount: 45,
    material: 'Thép không gỉ',
    size: '40mm',
    color: 'Đen',
    brand: 'Rolex',
    stockQuantity: 2,
    weight: 155.0,
    origin: 'Thụy Sĩ',
    isCertified: true,
    certificateNumber: 'ROLEX-2023-003',
  ),
  Jewelry(
    id: '6',
    name: 'Vòng tay trẻ em bạc PNJSilver 0000K000058',
    description:
        'Vòng tay bạc PNJSilver dành cho trẻ em với thiết kế tinh tế, chất liệu bạc cao cấp an toàn cho bé, mang lại vẻ ngoài đáng yêu và sang trọng.',
    price: 650000,
    imageUrls: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/137/sv0000k000058-vong-tay-tre-em-bac-pnjsilver-1.png',
    ],
    category: 'Vòng tay trẻ em',
    rating: 4.8,
    reviewCount: 112,
    material: 'Bạc S925',
    size: '13cm',
    color: 'Bạc',
    brand: 'PNJSilver',
    stockQuantity: 20,
    weight: 4.5,
    origin: 'Việt Nam',
    isCertified: true,
    certificateNumber: 'SILVER-2025-006',
  ),
  Jewelry(
    id: '7',
    name: 'Cặp nhẫn cưới Vàng 18K đính đá ECZ PNJ Chung Đôi 00878-00877',
    description:
        'Nhẫn cưới đôi vàng trắng 18K, thiết kế đơn giản thanh lịch, khắc tên miễn phí',
    price: 18000000,
    imageUrls: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/248/sp-gnxm00y000878-gnxm00y000877-cap-nhan-cuoi-vang-18k-dinh-da-ecz-pnj-chung-doi-1.png',
    ],
    category: 'Nhẫn',
    rating: 4.9,
    reviewCount: 234,
    material: 'Vàng trắng 18K',
    size: 'Đôi 16-18',
    color: 'Trắng',
    brand: 'Wedding Ring',
    stockQuantity: 10,
    weight: 7.5,
    origin: 'Việt Nam',
    isCertified: false,
  ),
  Jewelry(
    id: '8',
    name: 'Vòng Cổ Ngọc Bích Tự Nhiên',
    description:
        'Vòng cổ ngọc bích tự nhiên từ Myanmar, màu xanh đậm, chất lượng cao',
    price: 35000000,
    imageUrls: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=400&fit=crop',
    ],
    category: 'Vòng cổ',
    rating: 4.8,
    reviewCount: 67,
    material: 'Ngọc bích',
    gemstone: 'Ngọc bích',
    size: '55cm',
    color: 'Xanh',
    brand: 'Jade Master',
    stockQuantity: 3,
    weight: 45.0,
    origin: 'Myanmar',
    isCertified: true,
    certificateNumber: 'JADE-2023-005',
  ),
  Jewelry(
    id: '9',
    name: 'Cặp Nhẫn Đôi Titan',
    description:
        'Cặp nhẫn đôi titan không gỉ, thiết kế thể thao, phù hợp cho các cặp đôi trẻ',
    price: 2500000,
    imageUrls: [
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&h=400&fit=crop',
    ],
    category: 'Nhẫn',
    rating: 4.4,
    reviewCount: 145,
    material: 'Titan',
    size: 'Đôi 17-19',
    color: 'Xám',
    brand: 'Titan Sport',
    stockQuantity: 20,
    weight: 4.2,
    origin: 'Hàn Quốc',
    isCertified: false,
  ),
  Jewelry(
    id: '10',
    name: 'Bộ Trang Sức Cưới Hoàn Chỉnh',
    description:
        'Bộ trang sức cưới hoàn chỉnh gồm nhẫn, bông tai, dây chuyền vàng 18K đính kim cương',
    price: 85000000,
    imageUrls: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=400&fit=crop',
    ],
    category: 'Bộ trang sức',
    rating: 5.0,
    reviewCount: 28,
    material: 'Vàng 18K',
    gemstone: 'Kim cương',
    size: 'Bộ hoàn chỉnh',
    color: 'Vàng',
    brand: 'Luxury Set',
    stockQuantity: 2,
    weight: 25.8,
    origin: 'Việt Nam',
    isCertified: true,
    certificateNumber: 'SET-2023-006',
  ),
];

// Dữ liệu mẫu cho orders
final orders = [
  Order(
    id: 'DH001',
    userId: '1',
    customerName: 'Nguyễn Văn A',
    customerPhone: '0123456789',
    customerEmail: 'user01@example.com',
    deliveryAddress: '123 Đường Lê Duẫn, Quận 1, Tp.HCM',
    giftMessage: null,
    deliveryFee: 20000.0,
    discount: 0.0,
    insuranceFee: 0.0,
    totalAmount: 150000.0,
    status: OrderStatus.pending,
    paymentMethod: PaymentMethod.cash,
    orderTime: DateTime.now().subtract(const Duration(days: 2)),
    estimatedDeliveryDate: DateTime.now().add(const Duration(days: 3)),
    isGift: false,
    trackingNumber: null,
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    updatedAt: null,
    isDeleted: false,
  ),
  Order(
    id: 'DH002',
    userId: '1',
    customerName: 'Trần Thị B',
    customerPhone: '0987654321',
    customerEmail: 'user02@example.com',
    deliveryAddress: '456 Đường Nguyễn Đình Chiểu, Quận 3, Tp.HCM',
    giftMessage: 'Chúc mừng sinh nhật!',
    deliveryFee: 20000.0,
    discount: 0.0,
    insuranceFee: 10000.0,
    totalAmount: 300000.0,
    status: OrderStatus.delivered,
    paymentMethod: PaymentMethod.bankTransfer,
    orderTime: DateTime.now().subtract(const Duration(days: 5)),
    estimatedDeliveryDate: DateTime.now().subtract(const Duration(days: 1)),
    isGift: true,
    trackingNumber: 'TRACK12345',
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    updatedAt: null,
    isDeleted: false,
  ),
  Order(
    id: 'DH003',
    userId: '1',
    customerName: 'Lê Văn C',
    customerPhone: '0912345678',
    customerEmail: 'user03@example.com',
    deliveryAddress: 'Đường Phạm Hữu Lầu, Phường 6, Tp.Cao Lãnh, Tỉnh Đồng Tháp',
    giftMessage: null,
    deliveryFee: 20000.0,
    discount: 0.0,
    insuranceFee: 5000.0,
    totalAmount: 500000.0,
    status: OrderStatus.processing,
    paymentMethod: PaymentMethod.creditCard,
    orderTime: DateTime.now().subtract(const Duration(days: 1)),
    estimatedDeliveryDate: DateTime.now().add(const Duration(days: 2)),
    isGift: false,
    trackingNumber: 'TRACK67890',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    updatedAt: null,
    isDeleted: false,
  ),
];

// Dữ liệu mẫu cho order_details
final orderDetails = [
  // Đơn hàng DH001
  OrderDetail(
    id: 'od001',
    orderId: 'DH001',
    jewelryId: '1',
    quantity: 1,
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
    isDeleted: false,
  ),
  // Đơn hàng DH002
  OrderDetail(
    id: 'od002',
    orderId: 'DH002',
    jewelryId: '2',
    quantity: 2,
    createdAt: DateTime.now().subtract(const Duration(days: 6)),
    isDeleted: false,
  ),
  // Đơn hàng DH003
  OrderDetail(
    id: 'od003',
    orderId: 'DH003',
    jewelryId: '3',
    quantity: 1,
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    isDeleted: false,
  ),
];
// Dữ liệu mẫu cho favorite_jewelries
final favoriteJewelries = [
  {
    'id': 'fav001',
    'jewelryId': '1',
    'userId': '1',
    'addedAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'isDeleted': 0,
 
  },
  {
    'id': 'fav002',
    'jewelryId': '2',
    'userId': '1',
    'addedAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'isDeleted': 0,
  }
];

